# Generated by Django 4.0.1 on 2022-01-23 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('client', 'Client')], help_text='Role (Admin, Client)', max_length=10),
        ),
    ]
